### ISSUE TITLE
It would be better to connect with dpemote walk

### ISSUE THREAD

**Issue by haitham1337** [NathanERP/qb-walkingstyles#1]
It would be better to connect with dpemote walk

**Comment by Nathan-FiveM** [comment]
I'm working on adding it to the radial wheel, if you know how to help shoot me a DM

**Comment by haitham1337** [comment]
this new idea to store metadata

> 	PlayerData.metadata["walk"] = PlayerData.metadata["walk"] ~= nil and PlayerData.metadata["walk"] or "reset"

**Comment by haitham1337** [comment]
Are there any new news?
